" to run cmake from the project inside vim --> :make -C build/


" I need to add this because the company does not like my vimrc...
if getenv( "SAND" ) != v:null
   " if getenv is to new you have to use if expand( "$SAND" ) != "$SAND"
   " Using read command to get input from terminal commands example:
   " :r! find . -type f
   " --- Gets list of all files in current dir
   "


   let mapleader=" "

   set path+=**
   set wildmenu

   syntax on
   filetype plugin on

   set tabstop=3
   set shiftwidth=3
   set smartindent
   set number
   set relativenumber
   set hlsearch
   set expandtab
   set undodir=~/.vim/undodir
   set undofile
   set nocompatible
   set ruler
   set laststatus=2
   set noswapfile
   set showcmd
   set nowrap
   set ignorecase
   set smartcase
   set incsearch " To eanable ctrl g for search or press "d" then "/" then the word you want to delete and everthing from courser up to word will be deleted
   set ruler "to show column number
   set autoindent "to correctly indent after linbreak
   set scrolloff=8

   set hidden

   " Man pages it is
   " runtime ftplugin/man.vim
   " set keywordprg=:Man

   " Remove whitespace on space of each line
   autocmd BufWritePre * :%s/\s\+$//e

   "## LSP FAKE
   "\<CR\> = CTRL
   "CTAGS "LSP"
   "`<CR>]` to jump to a tag under the cursor
   "`g<CR>]` to get a listing of all matching tags
   "`<CR>t` to jump _back_ up the tag stack

   " <leader>f is :Format, see the format plugin. It pipes the buffer through
   " clang-format on stdin instead of clang-format -i, so the file on disk is
   " never touched and undo still works.

   " Rust Ctags stuff
   " Call rusty-tags vi to create ctags
   autocmd BufRead *.rs :setlocal tags=./rusty-tags.vi;/


   " Using vimgrep to find stuff if ctags doesnot work
   " vimgrep /FunctionName/gjf *
   " :help vimgrep
   " Slash wird benutzt um den such string mit den falgs zu trennen * für alle
   " folder
   " Dann normal mit :copen :cnext :cprev arbeiten
   "
   " Wenn es notwendig ist folder zu ignorieren:
   "     :set wildignore+=objd/**,obj/**,*.tmp,test.c
   " :help wildignore

   set wildignore+=objd/**,obj/**,*.tmp,*.o,*.d

   " For more stuff:
   " :help netrw-browse-maps
   let g:netrw_banner=0        " disable annoying banner
   let g:netrw_browse_split=4  " open in prior window
   let g:netrw_liststyle=3     " tree view
   "let g:netrw_list_hide=netrw_gitignore#Hide()
   "let g:netrw_list_hide.=',\(^\|\s\s\)\zs\.\S\+'

   " Switch to last open buffer
   nnoremap <leader><leader> :b #<CR>

   nnoremap <leader>x *``cgn
   nnoremap <leader>X #``cgn

   nnoremap <leader>n :cnext<CR>
   nnoremap <leader>p :cprev<CR>

   vnoremap <silent> <C-j> :move '>+1<CR>gv=gv
   vnoremap <silent> <C-k> :move '<-2<CR>gv=gv


   nnoremap <silent> <C-d> <C-d>zz
   nnoremap <silent> <C-u> <C-u>zz

   nnoremap <silent> gd <C-]>



   " <leader>gd is :GitDiff, see the gitdiff plugin.
   set diffopt+=context:99999

   " Cppreference
   set tags+=/Users/sandi/DEV/html-book-20240610



   " I have no idea
   command! -nargs=* -complete=shellcmd R new | setlocal buftype=nofile bufhidden=hide noswapfile | r !<args>

   " Format Logistix workflowutil. :FormatFile writes the buffer, runs the
   " tool on it and reloads - workflowUtil has no stdin mode.
   nnoremap <leader>lf :FormatFile workflowUtil -F -f %s<CR>



   " ---------------------------------------------------------------------
   " My own plugins. They live in ~/.vim/pack/sand/opt/<name> and vim finds
   " them there on its own - no plugin manager involved.
   "
   " To switch one off: comment out its line below.
   " To switch one off for good: delete its folder.
   " Most also honour g:<name>_no_mappings = 1 to keep the commands but drop
   " the key bindings. See :help <name>.
   " ---------------------------------------------------------------------

   " Directories worth a :find shortcut. <leader> + key, wildmenu does the rest.
   let g:projectfind_paths = {
         \ 'kb':   ['**/libs/entities/basetypes/',        'Knapp basetypes'],
         \ 'kc':   ['**/libs/logistix/ctxaccess/ctx',     'Knapp ctx access'],
         \ 'ksup': ['**/libs/components/suppliers/**/',   'Knapp suppliers'],
         \ 'kl':   ['**/libs/entities/lookup/',           'Knapp lookups'],
         \ 'ks':   ['libs/components/service/',           'Knapp services'],
         \ }

   " Header trees differ per host - work is linux, this box is not.
   if has('mac')
      let g:projectfind_paths['bg'] = ['/opt/homebrew/include/**/', 'brew headers']
      let g:projectfind_paths['bc'] = ['/Library/Developer/CommandLineTools/**/',
            \ 'CommandLineTools']
   else
      let g:projectfind_paths['bu'] = ['/usr/include/**/', 'system headers']
   endif

   " Names for the keyclue popup. projectfind adds its own on top of these.
   let g:keyclue_desc = {
         \ '<leader><leader>': 'last buffer',
         \ '<leader>f':  'format buffer',
         \ '<leader>lf': 'format with workflowUtil',
         \ '<leader>gd': 'diff against HEAD',
         \ '<leader>gD': 'close diff',
         \ '<leader>n':  'next quickfix',
         \ '<leader>p':  'previous quickfix',
         \ '<leader>x':  'change word, repeat with .',
         \ '<leader>X':  'change word backwards',
         \ '<leader>sf': 'find files',
         \ '<leader>sg': 'live grep',
         \ '<leader>sb': 'buffers',
         \ '<leader>sl': 'lines in this buffer',
         \ '<leader>a':  'harpoon: mark this file',
         \ '<leader>h':  'harpoon: menu',
         \ '<leader>1':  'harpoon: go to 1',
         \ '<leader>2':  'harpoon: go to 2',
         \ '<leader>3':  'harpoon: go to 3',
         \ '<leader>4':  'harpoon: go to 4',
         \ }

   " How long vim waits on an incomplete mapping - this is the delay before
   " the keyclue popup shows up. Type the full sequence faster than this and
   " you never see it.
   set timeoutlen=400

   for s:plugin in [
         \ 'tmux-navigate',
         \ 'projectfind',
         \ 'gitdiff',
         \ 'format',
         \ 'keyclue',
         \ 'pick',
         \ 'harpoon',
         \ ]
      execute 'packadd!' s:plugin
   endfor

endif
